
import java.awt.event.ActionEvent;

/**
 * <p>
 * @author Carlos Hoces
 * @author Javier Garcia
 */
public class JFrameButton extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrameButton
     */
    public JFrameButton() {
        initComponents();
        jButton1.addActionListener((ActionEvent e) -> {
            TestFrames.appEventBus.post("Boton pulsado en JFrame");
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
// <editor-fold defaultstate="collapsed" desc="Generated Code"> 
    private void initComponents() {

        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Botón");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(329, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

// Variables declaration - do not modify 
    private javax.swing.JButton jButton1;
// End of variables declaration 
}
